"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

# Pipes â•°â”€ â•­â”€
# Powerline symbols Â î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŠ  îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ” îƒ’
# Wedges ğŸ­§ğŸ­’ ğŸ­£ğŸ­§ğŸ­“
# Random noise ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—

format = """
$all\
$cmd_duration\
$sudo\
$username$hostname\
$directory\
$git_branch$git_status
$character
"""

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[â€¢ï‘„ ï‚©](bold fg:cyan) "
error_symbol = "[â€¢ï‘„ ó°…™](bold fg:red) "

[package]
symbol = "ó°— "
disabled = false

[git_branch]
style = "bg:blue"
symbol = "ó°˜¬"
truncation_length = 4
truncation_symbol = ""
format = "[îƒŠ ](bold fg:yellow)[ $symbol $branch(:$remote_branch) ](fg:black bg:yellow)[îƒˆ ](bold fg:yellow)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ï’¶ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = " [CONFLICTED](fg:red) "
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
untracked = " [UNTRACKED](fg:grey) "
stashed = " [STASHED] "
modified = " [MODIFIED](fg:yellow) "
staged = ' [STAGED](fg:green) '
renamed = " [RENAMED](fg:blue) "
deleted = " [DELETED](fg:red) "
format = '([$all_status$ahead_behind](fg:cyan bold))'

[hostname]
ssh_symbol = "î¬ "
ssh_only = false
format =  "[â€¢$hostname ](bg:blue bold fg:black)[îƒ† ](bold fg:blue )"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = "ó°› "
style = "bold dimmed green"

[time]
disabled = true
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:blue fg:black"
style_root = "red bold"
format = "[îƒ‡ ](bold fg:blue)[ $user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = " ï‘­ "
read_only = " ï‘– "
style = "bg:cyan fg:black"
truncation_length = 6
truncation_symbol = "â€¢â€¢/"
format = '[î‚¶](bold fg:cyan)[$path]($style)[î‚´ ](bold fg:cyan)'


[directory.substitutions]
"Desktop" = " ï’©  "
"Documents" = " ï’¥  "
"Downloads" = " ï‰  "
"Music" = " ó°ˆ "
"Pictures" = " ï  "
"Videos" = " ï”¬  "

[cmd_duration]
min_time = 0
format = '[îƒŠ ](bold fg:yellow)[î­± $duration](bold bg:yellow fg:black)[îƒˆ ](bold fg:yellow)'

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[c]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î˜ "

[conda]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "ï„Œ "

[crystal]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î˜¯ "

[dart]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î˜ "

[docker_context]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "ïŒˆ "

[elixir]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î˜­ "

[elm]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î˜¬ "

[fennel]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "îš¯ "

[golang]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î˜§ "

[guix_shell]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "ïŒ¥ "

[haskell]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î· "

[haxe]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î™¦ "

[java]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î‰– "

[julia]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î˜¤ "

[kotlin]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î˜´ "

[lua]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î˜  "

[meson]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "ó°”· "

[nim]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "ó°†¥ "

[nix_shell]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "ïŒ“ "

[nodejs]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "îœ˜ "

[ocaml]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î™º "

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[perl]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î™¾ "

[php]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î˜ˆ "

[pijul_channel]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "ï˜ "

[python]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "îˆµ "

[rlang]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "ó°Ÿ” "

[ruby]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î‘ "

[rust]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "ó±˜— "

[scala]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "îœ· "

[swift]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î• "

[zig]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "îš© "

[gradle]
format = '[îƒŠ ](bold fg:purple)[$symbol($version )](bold bg:purple fg:black)[îƒˆ ](bold fg:purple)'
symbol = "î™  "
